function wd_3dplot(zdata1,zmin,zmax,xcrop1,xcrop2,ycrop1,ycrop2)
%CREATEFIGURE(ZDATA1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 07-Jan-2014 13:08:20

% Create figure
figure1 = figure(20);

if nargin<2
    zmax=max(zdata1(:));
    zmin=min(zdata1(:));
elseif nargin<3
    zmax=max(zdata1(:));
end

% Crop Data - Comment out usually
zdata1=zdata1(ycrop1:ycrop2,xcrop1:xcrop2);

% Create axes
axes1 = axes('Parent',figure1,'CLim',[zmin zmax]);
%view(axes1,[-39.5 36]); %default view
view(axes1,[-10.5 58]);
grid(axes1,'on');
hold(axes1,'all');

% Create mesh
mesh(zdata1,'Parent',axes1,'Marker','.','LineStyle','none','FaceColor','none');
%mesh(zdata1,[0,2000,0,2000,0,0.06],'Parent',axes1,'Marker','.','LineStyle','none','FaceColor','none');
