function wd_3dplot(zdata1)
%CREATEFIGURE(ZDATA1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 07-Jan-2014 13:08:20

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-39.5 36]);
grid(axes1,'on');
hold(axes1,'all');

% Create mesh
mesh(zdata1,'Parent',axes1,'Marker','.','LineStyle','none','FaceColor','none');